### ISSUE TITLE
Reproducible build is needed

### ISSUE THREAD

**Issue by user6529576559** [standardnotes/android#1]
A reproducible build would be necessary to validate that the downloaded app from Google Play is the same as it would be if somebody compiles the source from github.

How it is done in Signal Private Messenger:
https://whispersystems.org/blog/reproducible-android/

**Comment by mobitar** [comment]
Yes, would love this. In due time.

**Comment by mobitar** [comment]
@deftelf can also speak to how difficult this would be. Would be great to have.

**Comment by deftelf** [comment]
I'm sure we're open to patches from @user6529576559  ;)

**Comment by mobitar** [comment]
Yes @user6529576559, reveal yourself :) But I think this would just be the way we distribute it.
