### ISSUE TITLE
Add support for pre-Lollipop

### ISSUE THREAD

**Issue by deftelf** [standardnotes/android#10]
Kitkat is important, might go to Jellybean too if it's not obviously a problem.

**Comment by mobitar** [comment]
The good thing about SN is it targets a somewhat tech-savvy crowd. With iOS, it only supports iOS 10 and above. Makes the code simpler and easier to maintain. Does it add a lot of complexity to add support for Kitkat?

**Comment by deftelf** [comment]
The compatibility libraries mean it's never too bad, but it is work.

**Comment by nbau21** [comment]
By "pre-Lollipop", I'm assuming you guys mean KitKat (4.4) or JellyBean (4.1) 

https://developer.android.com/about/dashboards/index.html

There's 2%~ of pre JellyBean devices around, and ~10% pre Lollipop devices.

In my experience supporting below Lollipop is a pain. Plus, by the time this app matures (who knows when?) there may be significantly less 'old' devices around.

Also given the crowd the app attracts as of today,  I would assume we all have newer than Lollipop.

**Comment by deftelf** [comment]
The bad one I think is KitKat, which is still at 22%. Having said that, in the western world it's much less, on an app I have in the UK, it's more like 7%.

Let's kick this one into the long grass. If we get serious traction worldwide we should do it, but that can always be added later.
