### ISSUE TITLE
Padding for tags

### ISSUE THREAD

**Issue by Lokesh-Krishna** [standardnotes/android#102]
Tags displayed in a note currently have barely any padding on either end within the box in which they rest. 
A little bit of padding would give the tags some room to breathe and give the app some polish.

**What it currently looks like**

![screenshot_20170428-222319](https://cloud.githubusercontent.com/assets/20235646/25538740/8936f308-2c61-11e7-9ccd-46fe320f9d7b.png)

**What it could look like** *(Google Keep)*

![screenshot_20170428-223649](https://cloud.githubusercontent.com/assets/20235646/25539134/5a4c799e-2c63-11e7-9efb-61a3a1959ec7.png)

**Comment by deftelf** [comment]
47438ae285f62747fe0f81aaa134acd2b4e27693
