### ISSUE TITLE
Delete note deleting wrong note

### ISSUE THREAD

**Issue by user6529576559** [standardnotes/android#106]
Hi,

I had 5-6 notes, I deleted the one at the bottom of the list, but it wasn't deleted, instead an other note has been deleted. I was able to reproduce the issue again because I didn't believe my eyes. I don't want to mess with it more because I don't want to lose my notes. :)

**Comment by deftelf** [comment]
Oh - that's not good! I haven't been able to reproduce locally, I will investigate.

**Comment by user6529576559** [comment]
Now I see there was an update 6 days ago which I haven't downloaded yet. Was anything changed regarding this in the update?

**Comment by deftelf** [comment]
I don't believe so

**Comment by mobitar** [comment]
@user6529576559 can you describe the steps you took to reproduce this issue?

**Comment by user6529576559** [comment]
Sadly, I cannot provide more info than I provided in my first post. Since then I couldn't reproduce this issue. Maybe it has to do something with threads and shared resources, if multiple thread using a same resource but locking is improperly implemented. I can't really think anything else right now.

**Comment by deftelf** [comment]
6496121963c5d28550d07c9daa2943d7ccea7ec2
It was possible if a sync happens between the user bringing the delete popup up and actually clicking yes on the confirmation dialog, for the assigned note to change. Won't happen much, but definitely can, entirely plausible this is what happened to you!
