### ISSUE TITLE
Auto-save while typing notes

### ISSUE THREAD

**Issue by mobitar** [standardnotes/android#11]
On iOS and web, we set up a timer that runs after a user makes a change to a note for 250ms that saves the note when fired. If another change is made within that 250ms window, the previous timer is canceled, and a new timer is set up.

**Comment by nbau21** [comment]
Does auto save mean auto sync with the server, or locally?

**Comment by mobitar** [comment]
Both.

**Comment by deftelf** [comment]
Sync still needed - NoteListFragment.sync() needs moving to an object that lives permanently, with events to let UI know when a sync is happening and when it's finished.
