### ISSUE TITLE
Add "Learn more about Standard Notes" in menu

### ISSUE THREAD

**Issue by mobitar** [standardnotes/android#111]
A lot of users yesterday downloaded the app directly from a review website, bypassing the standardnotes.org website. The problem with that is that they may not understand the full scope of what the ecosystem is, or what exactly they're using. Because on the surface you can't see much from the mobile apps.

So I added this to the iOS app:

![simulator screen shot may 3 2017 11 42 16 am](https://cloud.githubusercontent.com/assets/3277844/25671508/ede203aa-2ff5-11e7-9553-191c64a32883.png)

Simply opens the website:

![simulator screen shot may 3 2017 11 43 46 am](https://cloud.githubusercontent.com/assets/3277844/25671516/f04361ca-2ff5-11e7-9c06-8da29cbffe61.png)

**Comment by deftelf** [comment]
4e2aed6c38cb9e88ca24fea35540f6d23a1d690d
