### ISSUE TITLE
Hide "Server' field under advanced option

### ISSUE THREAD

**Issue by mobitar** [standardnotes/android#112]
More simple for most users.

<img width="282" alt="screen shot 2017-05-19 at 9 15 27 am" src="https://cloud.githubusercontent.com/assets/3277844/26251693/bfd62d08-3c73-11e7-9cfd-5dafc55ec483.png">
<img width="286" alt="screen shot 2017-05-19 at 9 15 39 am" src="https://cloud.githubusercontent.com/assets/3277844/26251692/bfd14bc6-3c73-11e7-813e-7be07697d10a.png">

Here also we relabeled "Standard File" to "Sync Server Domain", and changed the default from n3.standardnotes.org to sync.standardnotes.org. Same server. Just a different, easier to remember alias.

**Comment by deftelf** [comment]
be95ea7d111550796b6b430508ee0ed3fdde9b50
