### ISSUE TITLE
Deleting note locally - no action

### ISSUE THREAD

**Issue by mobitar** [standardnotes/android#118]
Report from user, feel free to close if can't replicate:

I want to report a bug in the Android app v1.3.0: If I try to delete an existing note, nothing happens. I am using the app locally, with no sync account. I am using a Huawei honor 8 smartphone with official ROM and Android Nougat.

**Comment by deftelf** [comment]
Oh, that's embarrassing...

Also, you can pull-to-refresh when not logged in.

**Comment by mobitar** [comment]
Haha ya I don't test much in offline mode either 😳

**Comment by deftelf** [comment]
311851820a56c0e2585e87f46fdf0d09b55c6a5b
