### ISSUE TITLE
Markdown is not being rendered

### ISSUE THREAD

**Issue by anavarre** [standardnotes/android#124]
If you have a markdown-powered editor with e.g. the Desktop or Web app, then you expect to also be able to see the rendered MD code with the Android app. But unfortunately this isn't working because the mobile app is fairly minimal. In the instance where you only have text, that's fine, surely you can manage to understand what's in the note. But in the case of images, they won't be rendered at all, thus leaving you with a poor UX. If you store your images e.g. in a Dropbox, then you also wouldn't be able to simply copy/paste the link in the browser because you wouldn't have the token authorization either.

**Comment by deftelf** [comment]
I'm afraid this is not on the plan at the moment #60
