### ISSUE TITLE
Deletion does not work

### ISSUE THREAD

**Issue by croo** [standardnotes/android#125]
Hi, i have just tried the app in search of a good brain dump program. For me the deletion of an entry hangs and never finishes, the app stops responding. I tried it offline, without any server account.
I made an arbitrary note with 1 tag, then tried to delete it. My device is a Motorola motog3 with v6.1.
L

**Comment by mobitar** [comment]
Thanks, this was actually fixed but is pending deploy. Only seems to happen when offline.

**Comment by croo** [comment]
Thanks for answering. I tried it with registration and it works just fine that way. Great app by the way :)
