### ISSUE TITLE
On The Colour Scheme

### ISSUE THREAD

**Issue by OriginalFannibal** [standardnotes/android#127]
I know this is a matter of preference but I just wanted to talk about this with y'all. I can't remember exactly where I read it but one of the official sources spoke about how Standard Notes integrated with whatever platform that you were using it on, be it desktop, Android or iOS.  

That said, is there any reason that the primary app colour on Android is red compared to the simple and calm neutral tones of the desktop app or the subtle use of red in the iOS app? I can only speak for myself but the red is a bit too flashy and "in your face". It is possible to have a Material Design app that has a white or grey colour scheme. That's what [Google Calendar]( https://play.google.com/store/apps/details?id=com.google.android.calendar&hl=en) does. Couple a white colour scheme with [dark status bar icons](https://stackoverflow.com/questions/33316668/how-to-change-the-status-bar-notification-icons-color-tint-in-android-marshmal) like Calendar does and you get a pretty classy look.  

The desktop app supports themes but I don't think that is something planned for the mobile apps, at least not to the same extent. I am not asking to add support for themes or switch the current colour scheme. Only to consider an alternate colour scheme. 

Looking forward to hearing what you think.

**Comment by mobitar** [comment]
Yes, I would love to give the Android app a face-lift :) It's the one app that I didn't have much of a hand in with the design, and @deftelf did an excellent job on the development, but he even admits he's not too handy with design stuff ;)

I'm looking to create a React Native implementation of the app that allows us to create a cross-platform solution with just 1 codebase. The cool thing about React Native is that it's not one of those hybrid solutions, but actually creates native apps on both platforms.

This way, it will be less expensive to maintain both apps in the future. To have an Android developer and an iOS developer on hand at all times is extremely expensive, so it's better if we can unify it and lessen our overhead.

With the React Native app, we might even be able to do things like theme-ing very easily.

Hoping to get started on it soon.

**Comment by OriginalFannibal** [comment]
React Native sounds amazing! Looking forward to it :)  
Should I close this issue or will this same repository host the new app when it is ready?

**Comment by mobitar** [comment]
No it will be a new repo. I think it's safe to close this.
