### ISSUE TITLE
Orbot support

### ISSUE THREAD

**Issue by user6529576559** [standardnotes/android#2]
Hello,

Although the notes are stored encrypted, so 2nd parties cannot read it, the fact that somebody is making notes is visible through metadata. This metadata is generated when somebody is accessing the standardfile server. This may seem an innocent act, but *in the future, maintaining a diary might be illegal*, especially if it is encrypted. Just remember Winston from 1984. APTs (advanced persistent threats (euphenism for government backed professional hacker groups who are actively participate in covert operations)) are then able to start targeted surveillance on individuals. If people have the ability to maintain a diary, then it would be harder for opressive regimes to commit history modifications by propaganda.

The Guardian Project created an Android app, called Orbot, which is a Tor service for Android. Apps like Orfox (Tor browser for android), ChatSecure (XMPP client with OTR) and Twitter have integrated Orbot support so it is possible to tunnel through the Tor network the app's connections without the need of rooting the phone. This have not just that benefit that the ISP won't know if the user is using StandardNotes, but it would be also possible to host the stadardfile server in a Tor Hidden Service, so the standardfile server's location would be also unknown by APTs.

**Comment by mobitar** [comment]
Interesting. So why is this an Android issue and not just a general issue for all platforms? And so how would this work? The server address you'd enter would be an onion address?

Also, let me know if you have any thoughts on this: https://github.com/standardfile/ruby-server/issues/8

**Comment by user6529576559** [comment]
Yes, it would be an onion address. Besides the physical location of the server would be unknown, there is an other advantage: the Tor network has its own encryption layers therefore it is independent from the flawed CA trust network.

ProtonMail has just announced recently their onion service, which sums up the topic pretty well: https://protonmail.com/blog/tor-encrypted-email/

Regarding the question about other platforms: in case of desktop platforms for every OS there is a general solution. Installing Qubes OS as the main OS allows to run multiple OSes virtually at the same time. There are VMs which are proxies for other VMs. The Whonix VMs (Gateway and Workstation) can tunnel all connections through Tor so this problem is solved generally for everything. (Whonix images can be run inside VirtualBox machines also so no need to change your native OS).

In case of iOS as far as I know there is no app yet which does the same as Orbot (because of license issues, but this information may be deprecated).

**Comment by mobitar** [comment]
What about a VPN server that then communicates with a Tor service? Is that possible?

**Comment by user6529576559** [comment]
It is possible but currently there are two main problems with VPNs in this case.
The first is the obvious one that you have to trust your VPN provider that it is not logging your requests before requesting it from Tor. I'm not familiar about how this works, I haven't used that kind of service yet, but in theory this could be possible.
Second is if the VPN disconnects (network issue), your OS will use your dragnet and your cover is then instantly blown. If you use a VM as a VPN proxy (and configure its firewall properly) then this latter case could not happen. Until today it is not possible to run VMs in mobile phones.
There is a third: DNS requests often not go through the VPN connection even if you are connected through VPN. This is called DNS leak.
