### ISSUE TITLE
Integrate crash reporting

### ISSUE THREAD

**Issue by deftelf** [standardnotes/android#27]
Also, go over code, check it's not leaking anything sensitive.

https://github.com/ACRA/acra

**Comment by herbig** [comment]
Is this in the works? Were you looking to do a basic setup, with reports sent via email, or something else in mind?

**Comment by deftelf** [comment]
I've set up a server and have implemented client locally, it's not working at the moment though...

**Comment by deftelf** [comment]
Implemented and pushed - the backend isn't working yet but I'm pretty sure the code is OK and doesn't break anything so I'm leaving it in disabled for now

**Comment by deftelf** [comment]
OK, this works at http://android-acra.standardnotes.org:5984/acralyzer/_design/acralyzer/index.html#/dashboard/
username: reporter2
password: reportit

It wants putting on a https server before we go live

**Comment by deftelf** [comment]
![image](https://cloud.githubusercontent.com/assets/233220/22929441/a8e8e32e-f2b3-11e6-885b-937ad117db48.png)

**Comment by deftelf** [comment]
https://deftelf.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/notes
