### ISSUE TITLE
Plausible deniability

### ISSUE THREAD

**Issue by user6529576559** [standardnotes/android#3]
Hello,

To keep the notes private, the notes are protected with a password. This provides protection only until the user is not threatened with a wrench or rubber-hose. If the user is forced to give out the password, the notes won't be private anymore.

This is why the user should be able to first enter the password and then, based on the entered password, different notes would be decrypted and shown. This could be accomplished by some kind of hidden volume mechanism, something similar how VeraCrypt implemented it in case of disk encryption. In this app, it could be implemented in file level, but the drawback would be that the file would have to be fixed size (like 10 or 100MB, could be configurable at first use). The whole file should be filled with random numbers initially and at the first few kBs there would be the headers. Based on the given password, it would try to decrypt the headers (until one is decrypted successfully). The decrypted header would contain the position in the file where it is possible to decrypt the random looking AES encrypted notes with the given password.

Syncing with the server would be even more complicated. We wouldn't want to transfer the whole file (10 or 100MB) every time we modify a few bytes. The synchronization should be solved by some kind of sync software like rsync. What is important that the indexes where the file has been modified should be sent encrypted of course. The problem is that the server would have to decrypt it to modify the file to finish the syncing process. This way the server will know what parts of the file has real notes and not just random data. But in case if the server is hosted as an onion service (Tor hidden service) and it is maintained by the user, then it is not that a big problem.

https://veracrypt.codeplex.com/wikipage?title=Hidden%20Volume

**Comment by mobitar** [comment]
I like you @user6529576559. You're going to take us to Bitcoin level security :) But yes this is very complex. I hope to do these kinds of things when I, and all of ours users, are 100% confident in every other aspect of the ecosystem, like apps, UX, reliability, redundancy, etc. But if we start doing these kinds of things now, it will most likely detract us from other, more practical tasks. But this is interesting. I'm going to explore your suggestions during free time. Thanks, and keep them coming.

**Comment by deftelf** [comment]
This is out of scope - we are not building for this and unlikely to succeed if we tried, it's a very complicated area that would add a huge amount of work with questionable success.
