### ISSUE TITLE
Monospace font for notes

### ISSUE THREAD

**Issue by kvj** [standardnotes/android#30]
Web version of standard notes uses monospace font for notes contents and it's cool. Shouldn't we also do same on Android? That would be nice, notes will look same on both platforms

**Comment by nbau21** [comment]
But.. it's not material 😅

**Comment by kvj** [comment]
Well, "Material Terminal" is Material and Monospace at same time :)
https://play.google.com/store/apps/details?id=yarolegovich.materialterminal

Material Design doesn't prohibit monospace font. We also can make font face configurable

**Comment by deftelf** [comment]
I think this should probably be a setting - personal preferences. I don't like monospace personally, but some do.
