### ISSUE TITLE
Export data option

### ISSUE THREAD

**Issue by mobitar** [standardnotes/android#32]
All clients should support basic exporting of data. On iOS, we do this by generating a JSON file then opening an email composer and setting the file as an attachment. This way the user can email it to themselves.

The user should also be able to choose whether they want the file to encrypted or decrypted. Encrypted means the content field of the JSON object is encrypted (not that the actual file is encrypted).

The exported file should be able to be imported successfully by the desktop/web apps.

**Comment by mobitar** [comment]
There's one small additional detail you'll need to know when working on this. Let me know if anyone volunteers to handle this issue and I'll post about it.

**Comment by herbig** [comment]
I started looking at this. Let me know what the issue is!

**Comment by deftelf** [comment]
Not sure, I think @mobitar will have to specify. You might need to have a look at the Swift implementation to see what that does: https://github.com/standardnotes/iOS/tree/4c56ebfa844e4599ba23effaecc44554b1f24647/standardnotes

**Comment by mobitar** [comment]
Namely that when you export the file, it has to include the user's auth_params. These are the things created during registration, or retrieved from the server before login. Here's a sample export file:

```
{
  "items": [
    {
      "uuid": "14ce317a-d960-43b9-8daf-2213ff3a6894",
      "content_type": "Note",
      "created_at": "2017-02-15T03:02:10.000Z",
      "content": "001AMEs1TCSlhfpxrhw1lL2HCbVQd2SLP4ZB7wMKBaBHcYLeYvmcJuxEgJwWEaOB+n+Cw6Ji6d1pJvu8i7mJT0uTw==",
      "enc_item_key": "oWLUTcZpmTI6ThSl5Ix/HX/W/aXKotm024HCRBzR5IHRy4lQSx1r846G119lO+BaL3p3dvb87Y0C2ginyuuvRwbwsnGsYHyKkHDQXCx0KCJRb9Ahb5gQsLTrVzlGspIv9Yqneco13uBv8MDWTW5RxgGesFqo1fYcYfz9th4yglkiUhCFR9Dl8+iiQw/3f8Nv",
      "auth_hash": "1b8915e305995bbb383a2976e37207c74cabfe2d0c2b890ab8b2f691b1646332",
      "updated_at": "2017-02-15T03:02:40.000Z"
    },
    {
      "uuid": "767A44F5-7AC4-4B06-8E49-EAB4D2045395",
      "content_type": "Note",
      "created_at": "2017-02-15T03:34:39.000Z",
      "content": "001P/oeFcPZtY23/1pmCori7Tk4o+O2JtaQ/0eSIMbR8it692+YPFvBZiT5owtyaQHk1UIzZzAm6/il1Dhg3yJ7cQ==",
      "enc_item_key": "07dDWdiFqgnJankWaWTzF5nFJBUvTg8+d/XqX5oLN0AasAuVqdity+1HmkmWHd4HfRzYZBf8ygsO3Nmq5oC+p2ZudyZPpn+3/4FTCjgSeBDvo+mLEzansWUkL8EXUwMPmDV9b9dDuoU+R2WHnYmXirnJ7TuwUV3u1zpC7dWZhtygghLoMQS2aorE6fMblqbB",
      "auth_hash": "42e8cd32df0ee487af746ca9a4df6b6736ea7c395b9e6470ba44ae87db745f3c",
      "updated_at": "2017-02-15T03:34:43.000Z"
    }
  ],
  "auth_params": {
    "pw_func": "pbkdf2",
    "pw_alg": "sha512",
    "pw_key_size": 512,
    "pw_cost": 5000,
    "pw_salt": "ee1ac3376ff54643fa24ed0398ccb978b773ad37"
  }
}
```

What I do is upon login/registration, I save these params as a JSON object to user preferences.

**Comment by herbig** [comment]
Ok, cool. I got this working last night, but am currently doing another auth params call when you export. I can cache the login params instead.

The only issue I was having was tag references weren't getting saved, so just need to figure out what's going on there and I should have a pull request coming..

**Comment by herbig** [comment]
A question for @deftelf: I have an object called PlaintextItem, which is essentially the same thing as EncryptedItem, which is just a wrapper for items where the content is not encrypted.

Does this make sense, or would it make more sense to rename EncryptedItem and use the same object?

**Comment by deftelf** [comment]
Probably rename the class I suppose and use the same one. Either that or make them both subclass the same abstract class that holds the actual data values. Hm, maybe that actually.
