### ISSUE TITLE
Registration feedback

### ISSUE THREAD

**Issue by nbau21** [standardnotes/android#38]
Upon successful registration, the user should see a success message of some form to confirm that an account has been created. Or a proper failure message if registration fails.

The app currently does nothing, except to forward the user to the `NoteListFragment`.

**Comment by Julesssss** [comment]
I've submitted a PR with this small addition. Perhaps in a future release we could replace Toasts with the SnackBar component, to align the app closer to Material Design. #43

**Comment by mobitar** [comment]
How do we currently handle password confirmation? Are there two fields?

**Comment by Julesssss** [comment]
If the user taps the Register button, a Dialog is displayed in which the user must retype their password.

![register_confirm_pass](https://cloud.githubusercontent.com/assets/10736861/23069684/4b18c042-f520-11e6-8c46-f3e4eeba4f21.png)

**Comment by mobitar** [comment]
Ok cool. Is it possible to add a message to that? Here's what we do on iOS:

![img_0369](https://cloud.githubusercontent.com/assets/3277844/23069739/379eac20-f4ee-11e6-92da-db6732948103.PNG)

**Comment by Julesssss** [comment]
Sure, could you create an issue for it and I'll submit another PR asap

**Comment by mobitar** [comment]
Yup, https://github.com/standardnotes/android/issues/44

**Comment by herbig** [comment]
I don't think we need a registration confirmation message, and if we did it would be better to be an AlertDialog on MainActivity welcoming the user or something like that.

This shows a toast notification, and it triggered in Crypt, which shouldn't have anything to do with the UI.

The underlying issue, that the user is taken to NoteListFragment, I think is because the server does not validate that the username is an email, so there is no such thing as a failed registration.

**Comment by nbau21** [comment]
+1 to @herbig! Let's keep UI related stuff to UI, it makes responsibilities separated.

**Comment by Julesssss** [comment]
Fair point, let's close this. Unfortunately there wasn't anything to differentiate between login and registration callbacks to LoginActivity so that was the simplest solution.

**Comment by mobitar** [comment]
> so there is no such thing as a failed registration.

It could fail in the case of duplicate email (or server error). But in iOS, there are two tabs on the bottom, "Notes" and "Account". The app starts in the Account tab. When the user successfully registers, it takes them to the Notes tab without any alert. Seems to be enough feedback.

**Comment by herbig** [comment]
Yeah true. Just explaining what Noel was likely experiencing with being
forwarded to the app on a "failed" registration.

We already have a toast notification for failed registrations, it's just
hard to trigger.

**Comment by nbau21** [comment]
This issue still needs to be open? I can close it if needed (not sure if Carl or mobitar can)

**Comment by deftelf** [comment]
Left if open but it probably be closed as it will be subsumed into a #45 ultimately
