### ISSUE TITLE
Auto Backup

### ISSUE THREAD

**Issue by herbig** [standardnotes/android#39]
Android auto backup syncs app files and shared preferences to your Google account, so that when you go to another phone, your data can go with you.

This keeps us logged into the app even if we uninstall it and reinstall.  Just making sure we don't want this before disabling with android:allowBackup="false"?

**Comment by deftelf** [comment]
Yeah we definitely don't want this plain out-of-the-box as it blows a hole in the security, let's disable completely for now. We might want to save the email and server for auto-populate, but the value in doing that is pretty small.
