### ISSUE TITLE
Android screen security

### ISSUE THREAD

**Issue by user6529576559** [standardnotes/android#4]
Signal Private Messenger has a feature which if enabled then it is not possible to make screenshots about the screen when the app is in foreground. This prevents also other apps to create screenshots about the notes. Also, when using the show open windows Android feature (the alt-tab-ish thing), the content of the app is not visible in the preview.
It would be nice to have this basic security measure in this app too.

**Comment by mobitar** [comment]
Other apps in Android can take screenshots of your app?

**Comment by deftelf** [comment]
Agreed, I will set the flag.

**Comment by Jules1991** [comment]
I think you're referring to the flag: WindowManager.FLAG_SECURE, would this not be better as an option under settings, rather than being used by default? While security is a priority, there are use cases where screenshotting notes to share with others could be useful.

**Comment by deftelf** [comment]
OK, will make it an option when we have an options screen...

**Comment by deftelf** [comment]
See #21
