### ISSUE TITLE
Add confirmation text to registration password alert

### ISSUE THREAD

**Issue by mobitar** [standardnotes/android#44]
![img_0369](https://cloud.githubusercontent.com/assets/3277844/23069850/9c7c5160-f4ee-11e6-8832-e5b62a84fb4f.PNG)

**Comment by Julesssss** [comment]
#46 

![reg_confirmation](https://cloud.githubusercontent.com/assets/10736861/23070510/2d317206-f523-11e6-8040-b030972ae398.png)
