### ISSUE TITLE
When a change comes in for the currently opened note, should update text view

### ISSUE THREAD

**Issue by mobitar** [standardnotes/android#48]
Not sure if this is already the case. I know it wasn't for iOS and I just had to add it due to user having sync conflicts because of this.

**Comment by herbig** [comment]
Ah, yeah I originally had this, but was having some issues with the short timer, where a sync could come in while you're typing and erase things. I noticed iOS didn't have it, so I cut it.

I'll take another look..

**Comment by mobitar** [comment]
Well, true that it could cut things when a change comes in, but most likely any conflicts would be handled by the server, which creates a copy in that case and sends it back to the app. So I wouldn't worry about it. Better to have consistent state on all user's devices.

**Comment by herbig** [comment]
Ah, the issue I had was just from the one mobile client. I would type a bit, pause, it would send a sync request, then if I continued typing before the request returned it would be out of sync with the next bit I'd typed in and clear it out.

**Comment by mobitar** [comment]
Oh you know what, there's a special way that iOS and web handle that. I'll create another issue.

**Comment by mobitar** [comment]
Well first — when you submit a change to the server, the server returns it in the `saved_items` array. What does Android do with this array? Anything?

**Comment by herbig** [comment]
Nothing currently.

**Comment by mobitar** [comment]
Ok then nevermind about the other issue. In that case, even if that happens, which I think would be pretty rare since you shouldn't be editing the same note on two clients at the same time, then it's not that big a deal since the changes you would lose are only the last second's worth of typing.

**Comment by deftelf** [comment]
We do handle the saved_items array, we merge the metadata only.

**Comment by mobitar** [comment]
Ok that's right.

**Comment by herbig** [comment]
Ah, yeah my mistake, we do sync the saved items.

**Comment by herbig** [comment]
Ahh, ok, so if the change occurred from the update I sent, it should be in the saved items array? And if the change occurred from another client, it will be in retrieved_items?

And you're only updating the view if it is in retrieved_items?

**Comment by deftelf** [comment]
Yes. The NoteFragment never gets updated while it's resumed.

**Comment by mobitar** [comment]
I think we should forego this one for the 1.0 release. Let's just get this thing out the door :)

**Comment by deftelf** [comment]
Agreed

**Comment by deftelf** [comment]
This is taken care of by #71 I believe
