### ISSUE TITLE
Minor alignment adjustments of composer

### ISSUE THREAD

**Issue by mobitar** [standardnotes/android#52]
Just a clean up of the rough edges. 

Before:
<img width="352" alt="screen shot 2017-02-19 at 9 30 01 am" src="https://cloud.githubusercontent.com/assets/3277844/23103772/4e64f79a-f686-11e6-8c9a-fe560482f3d3.png">

After:
![after](https://cloud.githubusercontent.com/assets/3277844/23103801/ab9cfa0c-f686-11e6-9b2e-98eb52eaca1a.png)

**Comment by deftelf** [comment]
ie fix alignments and spacing

**Comment by mobitar** [comment]
<img width="354" alt="screen shot 2017-02-19 at 10 36 34 am" src="https://cloud.githubusercontent.com/assets/3277844/23104237/4df72c7a-f68f-11e6-8243-67cffc1e11db.png">

Do we control the layout of the title and subtitle in the nav bar here? Of "Standard Notes" and "All notes". The subtitle is uncomfortably close to the edge. If we can control it, an adjustment of the subtitle by -2 px would make it look a little better.

**Comment by deftelf** [comment]
6c81cbc157a2860b200039d4c8496397ca84a5f3
