### ISSUE TITLE
Pure black and white in note list

### ISSUE THREAD

**Issue by mobitar** [standardnotes/android#55]
To match the composer, and other clients, we should make the bg here white and the title/text black. Date can remain a little faded.

<img width="351" alt="screen shot 2017-02-19 at 10 16 30 am" src="https://cloud.githubusercontent.com/assets/3277844/23104074/8242a49e-f68c-11e6-9e69-d3d7664dde31.png">

**Comment by kvj** [comment]
It was introduced by pull request #29

**Comment by herbig** [comment]
Ah, yeah I added that, in order to add a bit of contrast for the reveal animation.  If it's plain while we should definitely just remove the animation.

**Comment by mobitar** [comment]
I'm not sure what's causing delays in clicks (on physical device), but it might animations. Like when I go back from a note, the screen is frozen for a sec and I can't tap anything. I also see console messages of "Dropped 30 frames". Do you think this has something to do with animations? If so, might make sense to remove them.

**Comment by mobitar** [comment]
Also let's rename "Standard Notes" on the nav bar to just "Notes". The app should be mostly unbranded.

**Comment by herbig** [comment]
I don't think the animation would cause this. Are you seeing the un-reveal animation?

**Comment by mobitar** [comment]
I am seeing it yes. I see this message in the console:

> I/Choreographer: Skipped 32 frames!  The application may be doing too much work on its main thread.

**Comment by deftelf** [comment]
I don't think this is anything to do with the animation, it's probably because the app is doing unnecessary db access on the onPause / onResume, and that happens on the main thread at the moment. We haven't used it with the quantity of notes you have before.

**Comment by deftelf** [comment]
Right this lag has been fixed, was what I thought.
