### ISSUE TITLE
Don't update save status on every character change

### ISSUE THREAD

**Issue by tet3** [standardnotes/android#58]
In the Compose screen, the status line `Saving...` / `All Changes Saved` flickers back and forth on every "key" stroke. 

I'm actually not sure that I want all that save activity going to the remote server if I'm on cellular data rather than wifi.

**Comment by deftelf** [comment]
Also, support configurable continuous syncing. Should continuously sync / Should continuously sync when on unmetered connection / Should not continuously sync

**Comment by deftelf** [comment]
A delayed & faded indication would be less distracting - see Evernote / Google Docs

**Comment by mobitar** [comment]
On iOS and desktop, when a user types a character, a 500ms timer begins. When that timer fires, a sync is made. If the user types within the 500ms timer, then the old timer is cancelled a new one begins. This way a user can type on long continuous stream of say two sentences, and if he types fast enough, it will only be one sync.

**Comment by deftelf** [comment]
Same here

**Comment by nbau21** [comment]
> A delayed & faded indication would be less distracting - see Evernote / Google Docs
 
I like this.

Also, perhaps this is a good time to optimize the app's network request strategy. The app just attempts to sync on each key. What if connection is bad, would a different strategy (or a longer "wait" be better? 

See [[1](https://www.youtube.com/watch?v=nDHeuEM30ks&list=PLOU2XLYxmsIKEOXh5TwZEv89aofHzNCiu&index=2)] and [[2](https://developer.android.com/training/efficient-downloads/efficient-network-access.html)]

**Comment by deftelf** [comment]
It syncs after a delay of 250ms (which I agree should probably be longer). If the connection is bad and it takes time, it won't sync again until the first has finished. If there is no network then it doesn't try. I'm not particularly fussed about it since the power from the screen dwarves the power taken to do a little network. But if you have a better plan, happy to have it assuming it isn't too complicated.

**Comment by nbau21** [comment]
> But if you have a better plan, happy to have it assuming it isn't too complicated

I don't. I am happy as it is with the current strategy.

**Comment by deftelf** [comment]
Urgh, you can't get at the subtitle TextView in a toolbar easily... it's added at runtime and doesn't have an id or tag, and Toolbar has no method to manipulate it directly to do the fade! Gah!

**Comment by deftelf** [comment]
a9aaf6e1cec6ccdb8157db9f90bf978e63fa3228
