### ISSUE TITLE
Add Tag management

### ISSUE THREAD

**Issue by deftelf** [standardnotes/android#6]

**Comment by mobitar** [comment]
Does this mean like deleting tags? Or adding tags to notes?

**Comment by deftelf** [comment]
Both, though they might end up as separate tickets

**Comment by mobitar** [comment]
What's the most "standard" way to implement this on Android? Every OS seems to have it's own style. In web, it does it through a text input field where it accepts a # separated list of tags. On iOS, it's a table of tags with boolean switches next to each one, determining whether that tag is on or off for that note: 
 
![3 copy](https://cloud.githubusercontent.com/assets/3277844/22514333/a21016de-e864-11e6-9fc7-53e75cb6e1dc.png)

**Comment by deftelf** [comment]
Probably similar to this.

**Comment by deftelf** [comment]
Either with switches like that or checkboxes. Probably checkboxes because they match closer with what we're doing in my mind

**Comment by mobitar** [comment]
Ya checkboxes would have been nicer on iOS, but there was no native control for that. I would have had to custom build one. But custom UI is yucky.

**Comment by Julesssss** [comment]
It can be frustrating to search through a long list of tags though. I'm guessing we should match iOS as closely as possible, but the web implementation definately seems superior. Similar to Pocket, where you begin typing the tag and it will suggest tags you have already used.

**Comment by mobitar** [comment]
I actually don't think we should match iOS at all, but rather match what is the norm for Android apps. But true, if you have a lot of tags it could get messy, unless we add a search bar. But it's probably best to start with the simplest implementation possible just so we can get a 1.0 in the store, then make optimizations with time.

**Comment by deftelf** [comment]
I don't think there's any particular 'way' of doing this sort of thing that's natural to Android.

**Comment by mobitar** [comment]
Does the Android SDK have a stock checkbox element? Or would that have to be custom?

**Comment by deftelf** [comment]
https://developer.android.com/reference/android/widget/CheckBox.html

**Comment by Julesssss** [comment]
Google Keep also manages tags for individual notes with a list of Native checkboxes, seems like the right way to go.

**Comment by nbau21** [comment]
Kinda surprised it wasn't mentioned yet, but the Material Design have this component called [Chips](https://material.io/guidelines/components/chips.html)

Thankfully it's not that complicated to implement (assuming vanilla implementation) -> http://stackoverflow.com/a/41776777/4335897

Kinda sucks that you still have to do the leg work of writing the code for the `chips`. But I do think chips are the way to go for tags.

**Comment by nbau21** [comment]
I was thinking to implement what @Julesssss suggested. but the question is: how should users be able to reach this screen? should it be a menu item? text only or icon? which icon from https://material.io/icons/ ?

**Comment by deftelf** [comment]
@nbau21 I think for setting tags initially the most sensible thing would be to have a link in the action bar of the NoteActivity, either just the word TAGS or an icon if we can find one that takes you to the tag choosing activity.
Also clicking on preexisting tags in the Note would take you there too.

For filtering the list, I think @kvj populated navigation drawer makes sense, though that fork has a lot of accounts stuff that I'm not currently wanting to pull

**Comment by mobitar** [comment]
@kvj you're doing some beastly work :) But a pull request should only address 1 issue. This makes it easier to coordinate. Are you able to separate your work into separate requests? If you'd like to make tags as part of the account drawer, then first we should decide how we're going to merge the account drawer in, and whether that's the right decision. Thoughts?

**Comment by kvj** [comment]
@mobitar 
Yes, sure. I can do that. I'll extract navigation drawer and tag list into separate pull request

**Comment by herbig** [comment]
Is anyone working on the actual tagging in the note edit screen?

**Comment by kvj** [comment]
I'm planning to add note list filtering by tag in next few days

**Comment by deftelf** [comment]
I'm looking at it - I'll do a basic version today because it involves fiddling with NoteStore and that's a bit delicate.

**Comment by deftelf** [comment]
@kvj You might want to hold fire on that until I commit again - just changing how the tag stuff works.

**Comment by deftelf** [comment]
https://github.com/standardnotes/android/tree/tags

**Comment by Julesssss** [comment]
These are the best Material Icons I could find for notes.

<img width="268" alt="material_icons_notes" src="https://cloud.githubusercontent.com/assets/10736861/23072172/ae27377e-f528-11e6-96b1-af91470c8fc6.png">

**Comment by mobitar** [comment]
Are icons necessary? We don't want to add anything that we'll have to change as fashion changes ;) Just creates more work for the future.

**Comment by herbig** [comment]
@mobitar I wasn't fully aware of this philosophy when I started.

Should I kill the reveal animation stuff I added in before? It looks nice and all, but it's definitely in the realm of unnecessary code.

**Comment by mobitar** [comment]
Hmm..how many lines of code is it? If it's just a code block or so, maybe it doesn't hurt, but if there's substantial code and that code has tentacles, then maybe it would be best to remove it.

**Comment by herbig** [comment]
Yeah, it has some tentaclidge. Passing in XY coordinates to other screens so we know where to reveal / unreveal...

**Comment by mobitar** [comment]
> tentaclidge

Nice. I would say let the system handle animations and presentations. At least that's how it is for iOS - all presentation of view controllers is just done automatically. If Android doesn't do that, best not to support it. Coordinates will probably get tricky when it comes to tablets, testing on different screen sizes, etc. But, you guys are the Android experts. So let me know what you think.

**Comment by deftelf** [comment]
If it's already in there then leave it. This sort of thing isn't much work once it's been written. If it becomes a problem then we can remove it.

**Comment by mobitar** [comment]
The problem with removing things later, in general, is that it's a lot easier to remove something before anyone notices it. But once hundreds of people are dependent on it, and you remove it from under their feet, their app experience begins to feel subpar and lacking, and they begin to complain. This is a decision that should be made definitively one way or the other now and not later.

Also, see this tweet for inspiration ;) https://twitter.com/rauchg/status/813529770059186176

**Comment by deftelf** [comment]
The app should be pleasant to use. We're not talking about functionality, it's an animation. Nobody is dependent on a reveal animation so if it is removed it's hardly going to be the end of the world.
