### ISSUE TITLE
Render Markdown (or is this really "Support Extensions"?)

### ISSUE THREAD

**Issue by tet3** [standardnotes/android#60]
Would love to be able to view notes written in MD rendered as such in the app. 

Especially things like recipes or other reference notes that I've taken the time to mark up so that I can see them in their formatted glory.

**Comment by Lokesh-Krishna** [comment]
Can this please be evaluated independently of extensions support?  

Markdown support is something I take for granted on Simplenote and having migrated to Standard Notes, something I really miss on my phone. I markup my notes a lot for readability and unless it is rendered in markdown it actually makes things difficult.  

Would really appreciate if code formatting and syntax highlighting is supported too. Can't be the only one who saves blocks of code here, right?

**Comment by deftelf** [comment]
@mobitar what do you think? I'm getting the feeling that md might be a special case, seems quite high demand.

**Comment by mobitar** [comment]
The easy part of adding Markdown would be adding it. The real work starts when it's released. Trust me, I want Markdown in mobile more than anyone else. But there are a few reasons I'm holding back:

1. Adding a feature means you can never remove it. Users grow dependent on it and you'd be blasted to death in the reviews if you remove something. So if we add Markdown, we're adding it for life. That's not something I can commit to right now.
2. Adding it on Android means adding it to iOS. We don't have the resources to add, maintain, and QA something as big as Markdown on both platforms.
3. Adding Markdown means we have to maintain it. The world of Markdown is not binary - there are a lot of configuration options, with people wanting this flavor, or that functionality, or this parser. I learned this from the desktop Markdown editors. There are 3-4 separate editors out, yet people _still_ want some feature that's missing from all four of those. Adding Markdown to mobile means we will have to put up with a new wave of requests to fixing and modifying a 3rd party library. And we simply don't have the resources for that.
4. I want to explore a React Native app before independently making big changes to the iOS and Android app. This will allow us to have one native codebase, and also begin using things like custom themes and possibly extensions.
