### ISSUE TITLE
Crash bug opening SQLite db

### ISSUE THREAD

**Issue by deftelf** [standardnotes/android#63]
https://deftelf.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/notes/bug/6d53b766a570cc652686b44749f10b4b

**Comment by nbau21** [comment]
`android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14) : at org.standardnotes.notes.store.NoteStore.getReferences(NoteStore.kt:175)`

Huh, that's not very descriptive. I'm not looking into the code right now, but could it be that the user hasn't provided permissions at some point?

Could be that the db is being read by some other process too.

**Comment by deftelf** [comment]
Best theory at the moment is that different db objects are being returned for readableDatabase and they can't both read because it always happens in the inner query loop where there are two calls to readableDatabase, and two cursors open. Also, I wasn't closing the cursors... eep. So we'll see with the latest code 170918673322852586d303610a568d05c14a193c
