### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by takiainen** [standardnotes/android#68]
It's a secure, open source app store. The spirit of your note app project seem play well with the values of F-Droid.

**Comment by spiraldancing** [comment]
FWIW, I do not use Google Play store, for privacy concerns.  I intend to clone/compile the project for my Android phone, but keep putting it off because I'm lazy.  I do use F-Droid regularly.

Access thru F-Droid would be nice, and should help advance the project.

**Comment by IzzySoft** [comment]
If you could at least attach the `.apk` to the corresponding tags in `releases/` (see: [Creating Releases](https://help.github.com/articles/creating-releases/) in the GitHub Help: easy to do, doesn't take more than a minute), I could pick it up and add it to [my F-Droid compatible repo](https://android.izzysoft.de/repo). New releases then would be picked automatically within ~24h usually, so folks using the repo would automatically receive update informations and could install new versions easily.

**Comment by spiraldancing** [comment]
Could we at least start to include the .apk files in the releases, save me the trouble of learning how to compile Android apps from source (although, arguably, worth learning I suppose).

**Comment by deftelf** [comment]
Will do.

**Comment by deftelf** [comment]
If you could do this @IzzySoft then that would be much appreciated!

**Comment by IzzySoft** [comment]
@deftelf Now that the `.apk` is there, sure! Find it in my repo [here](https://apt.izzysoft.de/fdroid/index/apk/org.standardnotes.notes) (feel free to link for others to find). Welcome app #250 :smile_cat:

**Comment by deftelf** [comment]
Thanks!

**Comment by mobitar** [comment]
Thanks @IzzySoft! So how does this work now—how do other users find your repo?

**Comment by spiraldancing** [comment]
Thanks to all ... I've now got StandardNotes running on my Android phone 
w/o using Google Store.  I am happy.

1.  Visit the F-Droid site, install F-Droid to your phone.
-- This gives you access to all of the FOSS apps available in the 
default F-Droid repository.

2.  In the F-Droid app, there is a settings option to add repos. Just 
add the URL of IzzySoft's repo.

r

Let's go exploring.

**Comment by IzzySoft** [comment]
@mobitar as @spiraldancing described. That is, once they know about it. To let them know, you could update your [`README.md`](https://github.com/standardnotes/android/blob/master/README.md) and, right after the "This app can be downloaded from Google Play." add "or [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/org.standardnotes.notes)" :smile_cat: Instructions on adding the repo to the F-Droid client are given there.

And, @spiraldancing : preferably use the Repo URL given [there](https://android.izzysoft.de/repo), which is `https://apt.izzysoft.de/fdroid/repo`. I'm surprised it also works with the other one, which is just an integration into the Android site's structure :smile:

**Comment by mobitar** [comment]
Any chance someone can submit a pull to the readme to add those instructions?

**Comment by IzzySoft** [comment]
@mobitar being the owner of the project, you could simply edit the file directly at Github, there should be some "Edit" button visible to you when viewing the page :innocent:

**Comment by takiainen** [comment]
But why don't just add this into F-droid official repo and save the trouble of fiddling with additional repos?

**Comment by IzzySoft** [comment]
@takiainen 1) because it takes a while until an app is finally included with the official repo, 2) there's no harm having it available in both – provided it really *is* picked up finally, and 3) that way it is at least available immediately in a convenient manner to those not fond of Playstore? :innocent:

**Comment by cedricpim** [comment]
@mobitar was this ever added to the F-droid official repo?

**Comment by cedricpim** [comment]
Just saw this: https://github.com/standardnotes/mobile/issues/17 :+1:

**Comment by IzzySoft** [comment]
Doesn't look like. It's neither listed in main nor archive. The [corresponding RFP](https://gitlab.com/fdroid/rfp/issues/379) is still open, F-Droid was unable to build the app (follow there for reasons).

**Comment by atmoio** [comment]
I believe the F-Droid server is incapable of building React Native apps. Not sure if this has changed.

**Comment by IzzySoft** [comment]
@mobitar that was what I heard, yes. But recently I also heard there were already the first RN apps showing up. Might need checking with a maintainer (e.g. via the linked RFP).

**Comment by atmoio** [comment]
Thanks @IzzySoft, might need to revisit it at some point.
