### ISSUE TITLE
002 Encryption Type Support

### ISSUE THREAD

**Issue by mobitar** [standardnotes/android#70]
002 is an updated encryption scheme that properly handles IVs and auth hashes for both the item key and the content. This change addresses two issues:

1. Currently, only the content decryption is authenticated through HMAC, but the item key decryption should also be authenticated.
2. IVs for encryption were omitted initially because no content was ever encrypted twice with the same key, thus essentially replacing the IV. However what was overlooked is the enc_item_key is always being encrypted with the user's master key, so this needs an IV.

The change is not bad, and took me only about 10 minutes on both iOS and the web.

### How 002 encryption works:
Both `content` and `enc_item_key` will be encrypted with 002. Here's a sample 002 string:

`
002:78d2e1eec38897bc6c7e8bcf572e97b8912a9706523d0dba912b3cbddacd5012:d6694f6125e1c0c3b63953bf91717c8f:brcVwmuaoQAVzVDjf5oWFHLkiRiVCYKYgfeBFG4ZdmpdWiPm67Zh3f3CywmOfaLISbHVhxR5DC+x8zVPoHD6TCIJJVJP7/nVEuB6eTDJn1IrrLHQjyKQyouGJWrWDqw45zGf05cdhwvbm2vqMHnVa8KPSkjJmp8iFufDhQkbzwZkXTEM6yJQwBskDPC1WJHf
`

The string is divided into 4 components via a colon `:`.

```
comps = string.split(":")
```

- comps[0] is the version string.
- comps[1] is the authentication hash
- comps[2] is the IV
- comps[3] is the actual message/ciphertext.

### Item Encryption

In general, to encrypt a message with 002:

- Generate `iv = randomKey(128bits)`
- Generate `ciphertext = AESEncrypt(message, key, iv)`
- Set `stringToAuth = ["002", iv, ciphertext].join(":")`
- Generate `auth_hash = HMAC256(stringToAuth, authKey)`
- Assemble final string as `["002", auth_hash, iv, ciphertext].join(":")`

Since both `content` and `enc_item_key` are to be encrypted with 002, both need auth keys to use in HMAC. Currently, we only auth `content` using the second half of `enc_item_key`. However, since we're also encrypting `enc_item_key`, we need an auth key for this as well. 

So we need to come up with a global auth key that can be used for creating auth hashes for all item keys. To do this, we will derive new keys from the user's current master key `mk`.

We will generate two global level keys, an `encryptionKey` and an `authKey`. The derivation is simple:

- `encryptionKey = HMAC256(mk, "e")` That is, we put `mk` through HMAC using the literal string "e" as the key. 
- `authKey = HMAC256(mk, "a")` (Literal string "a" as key)

We'll generate these and save them on first run if they don't currently exist.

To encrypt an item: 

1. As with 001, generate a random token as the item_key. For 002 however, we'll encrypt item_key with the root level `encryptionKey`, and auth it with the root level `authKey` (according to the 002 encryption steps outlined above).
2. As with 001, split the item_key in half, using the first half as the item content's encryption key `ek` and the second half as the auth key `ak`. Encrypt the item's content using `ek` and auth it with `ak`.

### Decryption

In general, to decrypt an 002 string:

- Split the string into its components: `comps = string.split(":")`
- Set `remoteAuthHash = comps[1]`
- Set `stringToAuth = [ comps[0], comps[2], comps[3] ].join(":")`
- Compute `localAuthHash = HMAC256(stringToAuth, auth_key)`
- Make sure `remoteAuthHash == localAuthHash`. If not, skip decrypting this item.
- Decrypt `decrypt(messageToDecrypt: comps[3], iv: comps[2])`

To decrypt an item:

1. Decrypt the `enc_item_key` using the root level `encryptionKey` and auth it using the root level `authKey`. 
2. As with 001, split `enc_item_key` in half to get `ek` and `ak`, and decrypt the item's content using these relative keys, according to the 002 decryption instructions above.

## Important Notes

- If the user is using the web app which encrypts items with 002, but is using an outdated version of say the iOS app which only understands 001, then the user can potentially corrupt their data. In order to avoid this:
  - we will roll out updates to all platforms that have the _capability_ to encrypt/decrypt 002 strings, but do not yet actively encrypt in that format. These apps should continue encrypting in the 001 format, but if they receive an 002 string, they should handle it without issue. We will roll these out into the wild and let them propagate throughout a 30 day period, urging everyone to upgrade to these versions (autoupdate should handle most cases).
  - after the 30 day period is over, we will issue updates on all platforms that will begin encrypting with the 002 type. This should be as simple as flipping a switch - the apps should already have support for 002 encryption, it just wasn't enabled.

This issue is verbose as I wanted it to be very clear of the steps, but the implementation is pretty straightforward and should take no more than twenty minutes.

## Reference Implementations

Both iOS and Web have branches that currently properly support 002:

Web: https://github.com/standardnotes/web/pull/92
iOS: https://github.com/standardnotes/iOS/pull/35

To test, the staging app available at https://stagingapp.standardnotes.org will encrypt in 002 format (pending deploy), so you can sign in/create an account on stagingapi.standardnotes.org and sign in to the staging web app to create 002 items, which you can then test on mobile.

**Comment by mobitar** [comment]
I've updated standardfile.org with the 002 scheme:

https://standardfile.org/#encryption

**Comment by mobitar** [comment]
Production web app has been updated to understand and decrypt 002 (but does not yet actively encrypt in it). So it can be used to test decryption if needed. iOS app with the same change has also been submitted for review.

**Comment by deftelf** [comment]
d757773351f9d1a7e9a99b334fe8bbcc0b5f553d
