### ISSUE TITLE
Order of tags

### ISSUE THREAD

**Issue by justinkelly** [standardnotes/android#74]
The order of the tags in the Tags menu is different in the Android client compared to the web client

In the web clients its in alphabetical order

In the Android client I'm not sure what the order is - its not alphabetical, its not last used or by number of notes in a tag

Please can the list of tags be in the Android client be alphabetical to match the web client

**Comment by deftelf** [comment]
f3a86f7aedace65433684fff3a2791b10dcec14d

**Comment by deftelf** [comment]
f3a86f7aedace65433684fff3a2791b10dcec14d
