### ISSUE TITLE
Explain Option "Enable Screenshots"

### ISSUE THREAD

**Issue by thepill** [standardnotes/android#75]
Option should be explained.

Would like to submit a PR if someone tells me what this option means :)

**Comment by deftelf** [comment]
We are setting or not setting Window.FLAG_SECURE, so this is probably mis-named as a preference.

https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_SECURE

Essentially windows are secure by default, which prevents screenshots being taken, screenshots appearing in the recent apps list, or the Google Now screen search from working. If you want those things then the FLAG_SECURE cannot be used.

**Comment by thepill** [comment]
So we could just put the explaination from the dev side to it?

> treat the content of the window as secure, preventing it from appearing in screenshots or from being viewed on non-secure displays. 

Additional add the hint you mentioned about the recente apps list e.g.

**Comment by deftelf** [comment]
Pretty much, yes
