### ISSUE TITLE
Make sign up optional

### ISSUE THREAD

**Issue by mobitar** [standardnotes/android#90]
Offline mode by default. User can sign up when they wish. Offline notes are merged on signup.

For reference, the iOS app has two tabs on the bottom: Notes and Account.

<img width="259" alt="screen shot 2017-04-14 at 10 51 39 am" src="https://cloud.githubusercontent.com/assets/3277844/25048164/772bad50-2100-11e7-91b8-4204ead815fc.png">

When launching for the first time, the app starts in Notes. And the user is able to immediately start writing notes. Then, when the user wishes, they can tap on account and register, at which point all existing notes will be merged into the account.

**Comment by cr5315** [comment]
https://github.com/standardnotes/android/pull/96

**Comment by deftelf** [comment]
468f71a145119604cb58da76a16eb98b2e39a298

**Comment by deftelf** [comment]
v1.3
