### ISSUE TITLE
Password with character ñ fails login

### ISSUE THREAD

**Issue by mobitar** [standardnotes/android#94]
If you sign up for an account on web/desktop, and use the character `ñ` in your password, you will be unable to login on the Android app (and on iOS). Not sure what the issue is. Going to start investigating on iOS.

You can use this account to test:
u: kevintest@bitar.io
p: ñññ

**Comment by craig-s** [comment]
I have a pound sign (£) in my password, and am unable to log in using the web interface or desktop app. I've logged out of my Android app, and then back in, successfully - so it's not that I don't know what my password is.

**Comment by mobitar** [comment]
It's that the Android/iOS app for some reason treats those characters differently, so you can't sign in on web with it, and vice versa. If you had created your account on web, you can sign in there. I'm going to investigate this.

**Comment by mobitar** [comment]
Ok this was an encoding problem on the web. Fix deploying soon.

**Comment by mobitar** [comment]
See this update: https://blog.standardnotes.org/important-updates-to-passwords-with-international-characters
