### ISSUE TITLE
Ability to delete tags

### ISSUE THREAD

**Issue by mobitar** [standardnotes/android#97]

**Comment by craig-s** [comment]
I'll expand on that...

Once a new tag has been created, it can not be edited or deleted. This leaves the user unable to correct a tag that has been spelt correctly, or remove a tag created in error. There should be some facility to provide this functionality.

**Comment by mobitar** [comment]
On iOS you can delete a tag but not rename it. I think that's reasonable enough for now. We especially want to keep the mobile clients simpler because there's two separate codebases.

**Comment by deftelf** [comment]
c08ffa6c1d866c3dd19c1a3aa600b9cfd92f82c5
