### ISSUE TITLE
Blank Notes List

### ISSUE THREAD

**Issue by craig-s** [standardnotes/android#98]
When adding a new note via the _share with app_ function, the details are transferred into the app correctly and tags can be allocated. Fine. However, when exiting the newly entered note, the main notes list is empty. This can be refreshed by swiping down on the screen, or be re-selecting the _All Notes_ item in the _Navigation Drawer_ (which is already highlighted) - but it would be nice if the list was refreshed automatically.

**Comment by deftelf** [comment]
1f6c3848ed2be2f098e72016b2446ca61af75fd0
